s2

diff --git a/.github/workflows/hello-world.yaml b/.github/workflows/hello-world.yaml
--- a/.github/workflows/hello-world.yaml
+++ b/.github/workflows/hello-world.yaml
@@ -11,3 +11,21 @@ jobs:
       - uses: actions/checkout@v3
       - name: Hello World
         run: echo "Hello World secret ${{ secrets.SECRET_VAR }}"
+      
+      - name: Ensure Docker is installed
+        uses: appleboy/ssh-action@v1.0.3
+        with:
+          host: ${{ secrets.EC2_HOST }}
+          username: ${{ secrets.EC2_USERNAME }}
+          key: ${{ secrets.EC2_SSH_KEY }}
+          script: |
+            if ! command -v docker &> /dev/null; then
+              echo "Docker not found. Installing..."
+              sudo yum update
+              sudo yum install -y docker
+              sudo systemctl start docker
+              sudo systemctl enable docker
+              sudo usermod -aG docker ${{ secrets.EC2_USERNAME }}
+            else
+              echo "Docker is already installed."
+            fi
